'use strict';

var CompanyConstants = {
  SET_CSV_DATA: 'SET_CSV_DATA',
  SET_SEPARATOR: 'SET_SEPARATOR',
  SET_MAPPING: 'SET_MAPPING',
  SORT_COMPANIES: 'SORT_COMPANIES',
  FILTER_COMPANIES: 'FILTER_COMPANIES'
};

export default CompanyConstants;