'use strict';

var CompanyConstants = {
  SET_CSV_DATA: 'SET_CSV_DATA',
  SET_SEPARATOR: 'SET_SEPARATOR',
  SET_MAPPING: 'SET_MAPPING',
  SORT_COMPANIES: 'SORT_COMPANIES',
  FILTER_COMPANIES: 'FILTER_COMPANIES',
  SHOW_COMPANY_ON_MAP: 'SHOW_COMPANY_ON_MAP',
  HIDE_COMPANY_ON_MAP: 'HIDE_COMPANY_ON_MAP'
};

export default CompanyConstants;